# Generated by Django 4.2.4 on 2023-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_property_address_alter_property_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bulding_age',
        ),
        migrations.AddField(
            model_name='property',
            name='building_age',
            field=models.CharField(blank=True, choices=[('Less than one year', 'Less than one year'), ('1-5 Year', '1-5 Year'), ('5-10 Years', '5-10 Years'), ('More than 10 Years', 'More than 10 Years')], max_length=40, null=True, verbose_name='Select Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Houses', 'Houses'), ('Apartment', 'Apartment'), ('Villas', 'Villas'), ('Commercial', 'Commercial'), ('Garage', 'Garage')], max_length=40, null=True, verbose_name='Select Type'),
        ),
    ]
