# Generated by Django 4.2.4 on 2023-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('More than 5', 'More than 5')], max_length=40, null=True, verbose_name='Select Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('More than 5', 'More than 5')], max_length=40, null=True, verbose_name='Select Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bulding_age',
            field=models.CharField(blank=True, choices=[('Less than one year', 'Less than one year'), ('1-5 Year', '1-5 Year'), ('5-10 Years', '5-10 Years'), ('More than 10 Years', 'More than 10 Years')], max_length=40, null=True, verbose_name='Select Age of Bulding'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=40, null=True, verbose_name='Select Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('More than 2', 'More than 2')], max_length=40, null=True, verbose_name='Select Number of Grage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_renovated',
            field=models.CharField(blank=True, choices=[('Not Yet Renovated', 'Not Yet Renovated'), ('1-5 Year Before', '1-5 Year Before'), ('5-10 Years Before', '5-10 Years Before'), ('More than 10 Years Before', 'More than 10 Years Before')], max_length=40, null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Houses', 'Houses'), ('Apartment', 'Apartment'), ('Villas', 'Villas'), ('Commercial', 'Commercial'), ('Garage', 'Garage')], max_length=40, null=True, verbose_name='Select Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('More than 8', 'More than 8')], max_length=40, null=True, verbose_name='Select Total Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=40, null=True, verbose_name='Select State'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('For Sale', 'For Sale')], max_length=40, null=True, verbose_name='Select Property Status'),
        ),
    ]
