# Generated by Django 4.2.4 on 2023-09-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_alter_property_features_alter_property_major_road_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='major_road',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 1 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_hospital',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 1 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_supermarket',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 1 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
    ]
