# Generated by Django 4.2.4 on 2023-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='thumbnail/')),
                ('video', models.FileField(default='', null=True, upload_to='videos/')),
                ('owner_name', models.CharField(max_length=30, verbose_name='Owner Name')),
                ('property_type', models.CharField(max_length=100, verbose_name='property_type')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('bedrooms', models.CharField(max_length=100, verbose_name='BedRooms')),
                ('bathrooms', models.CharField(max_length=100, verbose_name='BethRooms')),
                ('rooms', models.CharField(max_length=100, verbose_name='Rooms')),
                ('garage', models.CharField(max_length=100, verbose_name='Garage')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.IntegerField(verbose_name='Zipcode')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('bulding_age', models.CharField(max_length=100, verbose_name='Bulding Age')),
                ('floor', models.CharField(default='', max_length=100, verbose_name='floor')),
                ('floor_plan', models.FileField(default='', upload_to='floorplan/')),
                ('last_renovated', models.CharField(default='', max_length=100, verbose_name='Last Renovated')),
                ('whatsapp_no', models.IntegerField(verbose_name='WhatsApp_Number')),
                ('features', models.CharField(blank=True, max_length=200, verbose_name='Features')),
            ],
        ),
    ]
