# Generated by Django 4.2.4 on 2023-09-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_property_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.CharField(blank=True, choices=[('Air Condition', 'Air Condition'), ('Playing Area', 'Playing Area'), ('Well', 'Well')], max_length=255, null=True),
        ),
    ]
