# Generated by Django 4.2.4 on 2023-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_alter_property_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='major_road',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilo Meter', 'Less than 10 Kilo Meter'), ('1-5 Kilo Meter', '1-5 Kilo Meter'), ('5-10 Kilo Meter', '5-10 Kilo Meter'), ('More than 10 Kilo Meter', 'More than 10 Kilo Meter')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='near_hospital',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilo Meter', 'Less than 10 Kilo Meter'), ('1-5 Kilo Meter', '1-5 Kilo Meter'), ('5-10 Kilo Meter', '5-10 Kilo Meter'), ('More than 10 Kilo Meter', 'More than 10 Kilo Meter')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='near_supermarket',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilo Meter', 'Less than 10 Kilo Meter'), ('1-5 Kilo Meter', '1-5 Kilo Meter'), ('5-10 Kilo Meter', '5-10 Kilo Meter'), ('More than 10 Kilo Meter', 'More than 10 Kilo Meter')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.CharField(max_length=255),
        ),
    ]
