# Generated by Django 4.2.4 on 2023-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_property_major_road_property_near_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='major_road',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 10 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_hospital',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 10 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='near_supermarket',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Less than 1 Kilometer', 'Less than 10 Kilometer'), ('1-5 Kilometer near', '1-5 Kilometer'), ('5-10 Kilometer', '5-10 Kilometer'), ('More than 10 Kilometer', 'More than 10 Kilometer')], max_length=40, null=True),
        ),
    ]
