# Generated by Django 4.2.4 on 2023-09-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
