# Generated by Django 4.2.4 on 2023-09-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_rename_city_property_twon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Twon',
            new_name='Town',
        ),
    ]
