# Generated by Django 4.2.4 on 2023-09-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_property_view_count_propertyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_no',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Ground Floor', 'Ground Floor'), ('1 Floor', '1 Floor'), ('2 Floor', '2 Floor'), ('3 Floor', '3 Floor'), ('4 Floor', '4 Floor'), ('5 Floor', '5 Floor'), ('6 Floor', '6 Floor'), ('7 Floor', '7 Floor'), ('8 Floor', '8 Floor'), ('9 Floor', '9 Floor'), ('10 Floor', '10 Floor'), ('11 Floor', '11 Floor'), ('12 Floor', '12 Floor'), ('13 Floor', '13 Floor'), ('14 Floor', '14 Floor'), ('15 Floor', '15 Floor'), ('16 Floor', '16 Floor'), ('17 Floor', '17 Floor'), ('18 Floor', '18 Floor'), ('19 Floor', '19 Floor'), ('20 Floor', '20 Floor'), ('21 Floor', '21 Floor'), ('22 Floor', '22 Floor'), ('23 Floor', '23 Floor'), ('24 Floor', '24 Floor'), ('25 Floor', '25 Floor'), ('26 Floor', '26 Floor'), ('27 Floor', '27 Floor'), ('28 Floor', '28 Floor'), ('29 Floor', '29 Floor'), ('30 Floor', '30 Floor'), ('31 Floor', '31 Floor'), ('32 Floor', '32 Floor'), ('33 Floor', '33 Floor'), ('34 Floor', '34 Floor'), ('35 Floor', '35 Floor'), ('36 Floor', '36 Floor'), ('37 Floor', '37 Floor'), ('38 Floor', '38 Floor'), ('39 Floor', '39 Floor'), ('40 Floor', '40 Floor'), ('41 Floor', '41 Floor'), ('42 Floor', '42 Floor'), ('43 Floor', '43 Floor'), ('44 Floor', '44 Floor'), ('45 Floor', '45 Floor'), ('46 Floor', '46 Floor'), ('47 Floor', '47 Floor'), ('48 Floor', '48 Floor'), ('49 Floor', '49 Floor'), ('50 Floor', '50 Floor'), ('51 Floor', '51 Floor'), ('52 Floor', '52 Floor'), ('53 Floor', '53 Floor'), ('54 Floor', '54 Floor'), ('55 Floor', '55 Floor'), ('56 Floor', '56 Floor'), ('57 Floor', '57 Floor'), ('58 Floor', '58 Floor'), ('59 Floor', '59 Floor'), ('60 Floor', '60 Floor'), ('61 Floor', '61 Floor'), ('62 Floor', '62 Floor'), ('63 Floor', '63 Floor'), ('64 Floor', '64 Floor'), ('65 Floor', '65 Floor'), ('66 Floor', '66 Floor'), ('67 Floor', '67 Floor'), ('68 Floor', '68 Floor'), ('69 Floor', '69 Floor'), ('70 Floor', '70 Floor'), ('71 Floor', '71 Floor'), ('72 Floor', '72 Floor'), ('73 Floor', '73 Floor'), ('74 Floor', '74 Floor'), ('75 Floor', '75 Floor'), ('76 Floor', '76 Floor'), ('77 Floor', '77 Floor'), ('78 Floor', '78 Floor'), ('79 Floor', '79 Floor'), ('80 Floor', '80 Floor'), ('81 Floor', '81 Floor'), ('82 Floor', '82 Floor'), ('83 Floor', '83 Floor'), ('84 Floor', '84 Floor'), ('85 Floor', '85 Floor'), ('86 Floor', '86 Floor'), ('87 Floor', '87 Floor'), ('88 Floor', '88 Floor'), ('89 Floor', '89 Floor'), ('90 Floor', '90 Floor')], max_length=40, null=True),
        ),
    ]
